import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import { Poppins } from 'next/font/google';

const poppins =  Poppins({
    subsets: ["latin", "latin-ext"],
    weight: ["100", "200", "400", "500", "600", "700", "800", "900"]
})
const inter = Inter({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen h-screen`}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
